### ISSUE TITLE
希望能私聊请教一些问题

### ISSUE THREAD

**Issue by rainym00d** [WANDY666/MusicApp#1]
您好  我是RUC的本科生  因为最近在学习前端的时候遇到一些问题  所以想请教一些关于前端学习路线的疑惑
如果可以的话  想加微信私聊

**Comment by WANDY666** [comment]
哈哈哈，真的吗，我也是新学的，BUAA的，请教算不上，也就是交流吧。W13835755840，这是我的微信号。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WANDY666/MusicApp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月9日(星期六) 中午1:13
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[WANDY666/MusicApp] 希望能私聊请教一些问题 (#1)





 
您好  我是RUC的本科生  因为最近在学习前端的时候遇到一些问题  所以想请教一些关于前端学习路线的疑惑
 如果可以的话  想加微信私聊
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
